### ISSUE TITLE
bug in function pad()

### ISSUE THREAD

**Issue by claforte** [lmammino/vtt-creator#1]
Hi, thanks for sharing this useful code. I noticed a bug in function pad(), that results in incorrect padding on 9:

e.g. "00:00:05.923 --> 00:00:9.026"
instead of:
"00:00:05.923 --> 00:00:09.026"

Here's a fix:
function pad(num) {
  if (num < 10) {
    return '0' + num;
  }
...

If you could update your npm as well that would be awesome. Thanks!

Christian

**Comment by lmammino** [comment]
This is now fixed. Will be in npm in seconds! Thanks a million for finding and reporting this out! 👌

**Comment by claforte** [comment]
Hi Luciano, no, thank you for developing it in the first place and maintaining it. ☺

Christian Laforte
CTO, Fortem
Toll-free: 877-607-8919 #201
Direct:    514-849-6068 #201
